[tool.poetry]
name = "store"
version = "0.1.0"
description = ""
authors = ["Komarov Sergey <onubee@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.12"
Django = "^5.0.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
